export const companiesData = [
  {
    name: 'TechViet Solutions',
    email: 'hr@techviet.com',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=TechViet',
    websiteUrl: 'https://techviet.com',
    location: 'Ho Chi Minh City, Vietnam',
    description: 'Leading software development company specializing in web and mobile applications for international clients.',
  },
  {
    name: 'VietSoft Technologies',
    email: 'careers@vietsoft.vn',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=VietSoft',
    websiteUrl: 'https://vietsoft.vn',
    location: 'Hanoi, Vietnam',
    description: 'Innovative technology company focused on AI and machine learning solutions for enterprise clients.',
  },
  {
    name: 'Saigon Digital',
    email: 'jobs@saigondigital.com',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=SaigonDigital',
    websiteUrl: 'https://saigondigital.com',
    location: 'Ho Chi Minh City, Vietnam',
    description: 'Digital agency providing comprehensive web development, mobile apps, and digital marketing services.',
  },
  {
    name: 'FPT Software',
    email: 'recruitment@fpt.com',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=FPT',
    websiteUrl: 'https://fpt-software.com',
    location: 'Multiple locations, Vietnam',
    description: 'Global technology and software services company with expertise in digital transformation.',
  },
  {
    name: 'VNG Corporation',
    email: 'hr@vng.com.vn',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=VNG',
    websiteUrl: 'https://vng.com.vn',
    location: 'Ho Chi Minh City, Vietnam',
    description: 'Leading internet and technology corporation in Vietnam, creator of Zalo and other popular platforms.',
  },
  {
    name: 'Tiki Technology',
    email: 'careers@tiki.vn',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=Tiki',
    websiteUrl: 'https://tiki.vn',
    location: 'Ho Chi Minh City, Vietnam',
    description: 'Vietnam\'s leading e-commerce platform with innovative technology solutions.',
  },
  {
    name: 'Grab Vietnam',
    email: 'careers.vn@grab.com',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=Grab',
    websiteUrl: 'https://grab.com/vn',
    location: 'Ho Chi Minh City, Vietnam',
    description: 'Southeast Asia\'s leading super app providing transportation, food delivery, and financial services.',
  },
  {
    name: 'Sendo Technology',
    email: 'jobs@sendo.vn',
    password: 'password123',
    logoUrl: 'https://via.placeholder.com/200x200?text=Sendo',
    websiteUrl: 'https://sendo.vn',
    location: 'Ho Chi Minh City, Vietnam',
    description: 'Fast-growing e-commerce platform connecting consumers with local businesses across Vietnam.',
  },
];