import { ExperienceLevel, JobType } from '../common/enums';

export const jobPostsData = [
  {
    title: 'Senior Backend Developer',
    description:
      'We are looking for an experienced Backend Developer to join our team. You will be responsible for developing and maintaining server-side applications using Node.js and NestJS. Experience with MongoDB and microservices architecture is required.',
    companyName: 'TechViet Solutions',
    categoryName: 'Backend Development',
    skillNames: ['Node.js', 'NestJS', 'MongoDB', 'TypeScript'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 2000,
    salaryMax: 3500,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.SENIOR,
    isActive: true,
    expiresAt: new Date('2024-12-31'),
  },
  {
    title: 'Frontend React Developer',
    description:
      'Join our frontend team to build amazing user interfaces using React.js and modern web technologies. You will work closely with designers and backend developers to create responsive and user-friendly applications.',
    companyName: 'VietSoft Technologies',
    categoryName: 'Frontend Development',
    skillNames: ['React.js', 'TypeScript', 'CSS', 'HTML'],
    location: 'Hanoi, Vietnam',
    salaryMin: 1500,
    salaryMax: 2800,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    isActive: true,
    expiresAt: new Date('2024-11-30'),
  },
  {
    title: 'Full Stack Developer',
    description:
      'We need a versatile Full Stack Developer who can work on both frontend and backend. Experience with React.js, Node.js, and database design is essential. You will be part of a small agile team building innovative products.',
    companyName: 'Saigon Digital',
    categoryName: 'Full Stack Development',
    skillNames: ['React.js', 'Node.js', 'Express.js', 'MongoDB'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 1800,
    salaryMax: 3000,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    isActive: true,
    expiresAt: new Date('2024-12-15'),
  },
  {
    title: 'Mobile App Developer - React Native',
    description:
      'Looking for a skilled Mobile Developer to build cross-platform mobile applications using React Native. Experience with publishing apps to App Store and Google Play is preferred.',
    companyName: 'FPT Software',
    categoryName: 'Mobile Development',
    skillNames: ['React Native', 'JavaScript', 'iOS', 'Android'],
    location: 'Multiple locations, Vietnam',
    salaryMin: 1600,
    salaryMax: 2700,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    isActive: true,
    expiresAt: new Date('2024-12-20'),
  },
  {
    title: 'DevOps Engineer',
    description:
      'We are seeking a DevOps Engineer to help us scale our infrastructure. You will work with Docker, Kubernetes, AWS, and CI/CD pipelines. Experience with monitoring and security best practices is highly valued.',
    companyName: 'VNG Corporation',
    categoryName: 'DevOps',
    skillNames: ['Docker', 'Kubernetes', 'AWS', 'Jenkins'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 2200,
    salaryMax: 4000,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.SENIOR,
    isActive: true,
    expiresAt: new Date('2025-01-31'),
  },
  {
    title: 'Data Scientist',
    description:
      'Join our data team to build machine learning models and analyze large datasets. You will work with Python, TensorFlow, and various data visualization tools to drive business decisions.',
    companyName: 'Tiki Technology',
    categoryName: 'Data Science',
    skillNames: ['Python', 'Machine Learning', 'TensorFlow', 'SQL'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 2000,
    salaryMax: 3500,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.SENIOR,
    isActive: true,
    expiresAt: new Date('2024-12-10'),
  },
  {
    title: 'QA Automation Engineer',
    description:
      'We need a QA Engineer to design and implement automated testing frameworks. Experience with Selenium, Jest, and API testing is required. You will ensure the quality of our products.',
    companyName: 'Grab Vietnam',
    categoryName: 'Quality Assurance',
    skillNames: ['Selenium', 'Jest', 'Postman', 'JavaScript'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 1400,
    salaryMax: 2500,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    isActive: true,
    expiresAt: new Date('2024-11-25'),
  },
  {
    title: 'UI/UX Designer',
    description:
      'Looking for a creative UI/UX Designer to design beautiful and intuitive user interfaces. Experience with Figma, user research, and prototyping is essential. You will work closely with product managers and developers.',
    companyName: 'Sendo Technology',
    categoryName: 'UI/UX Design',
    skillNames: ['Figma', 'Adobe XD', 'Photoshop', 'User Research'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 1200,
    salaryMax: 2200,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    isActive: true,
    expiresAt: new Date('2024-12-05'),
  },
  {
    title: 'Junior Backend Developer',
    description:
      'Great opportunity for a Junior Developer to start their career in backend development. You will learn modern technologies and work on real projects with mentorship from senior developers.',
    companyName: 'TechViet Solutions',
    categoryName: 'Backend Development',
    skillNames: ['Node.js', 'JavaScript', 'MongoDB', 'Express.js'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 800,
    salaryMax: 1500,
    jobType: JobType.FULL_TIME,
    experienceLevel: ExperienceLevel.ENTRY,
    isActive: true,
    expiresAt: new Date('2024-12-31'),
  },
  {
    title: 'Part-time Frontend Developer',
    description:
      'Flexible part-time position for Frontend Developer. Perfect for students or professionals looking for additional income. Work on interesting projects using modern React.js stack.',
    companyName: 'Saigon Digital',
    categoryName: 'Frontend Development',
    skillNames: ['React.js', 'CSS', 'JavaScript', 'HTML'],
    location: 'Ho Chi Minh City, Vietnam',
    salaryMin: 600,
    salaryMax: 1200,
    jobType: JobType.PART_TIME,
    experienceLevel: ExperienceLevel.ENTRY,
    isActive: true,
    expiresAt: new Date('2024-11-30'),
  },
];
