export const usersData = [
  {
    name: 'Nguyen Van An',
    email: 'nguyenvanan@example.com',
    password: 'password123',
    phone: '+84901234567',
    avatarUrl: 'https://via.placeholder.com/150x150?text=An',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-An',
  },
  {
    name: 'Tran Thi Binh',
    email: 'tranthibinh@example.com',
    password: 'password123',
    phone: '+84912345678',
    avatarUrl: 'https://via.placeholder.com/150x150?text=Binh',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-Binh',
  },
  {
    name: 'Le Van Cuong',
    email: 'levancuong@example.com',
    password: 'password123',
    phone: '+84923456789',
    avatarUrl: 'https://via.placeholder.com/150x150?text=Cuong',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-Cuong',
  },
  {
    name: 'Pham Thi Dung',
    email: 'phamthidung@example.com',
    password: 'password123',
    phone: '+84934567890',
    avatarUrl: 'https://via.placeholder.com/150x150?text=Dung',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-Dung',
  },
  {
    name: 'Hoang Van Em',
    email: 'hoangvanem@example.com',
    password: 'password123',
    phone: '+84945678901',
    avatarUrl: 'https://via.placeholder.com/150x150?text=Em',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-Em',
  },
  {
    name: 'Vu Thi Fong',
    email: 'vuthifong@example.com',
    password: 'password123',
    phone: '+84956789012',
    avatarUrl: 'https://via.placeholder.com/150x150?text=Fong',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-Fong',
  },
  {
    name: 'Do Van Giang',
    email: 'dovangiang@example.com',
    password: 'password123',
    phone: '+84967890123',
    avatarUrl: 'https://via.placeholder.com/150x150?text=Giang',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-Giang',
  },
  {
    name: 'Bui Thi Ha',
    email: 'buithiha@example.com',
    password: 'password123',
    phone: '+84978901234',
    avatarUrl: 'https://via.placeholder.com/150x150?text=Ha',
    resumeUrl: 'https://via.placeholder.com/400x600?text=Resume-Ha',
  },
];
